# Copyright (c) 2022-2025 Broadcom. All Rights Reserved.
# Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
# and/or its subsidiaries.

""" Driver definition for nvme_pcie driver.
"""

load(
    "//bora/bazel/esx:device_driver.bzl",
    "device_driver",
)
load(
    "//bora/bazel/esx/package/vibs:driver_package.bzl",
    "add_binary_payload",
    "define_device_spec",
    "driver_package",
)
load(":nvme_pcie_devices.bzl", NVME_PCIE_DEV = "DEV")

_DRIVER_NAME = "nvme_pcie"

_BINARY_COMPAT = "yes"

_VENDOR = "VMware"

_DRIVER_VER = "1.4.0.5"

_VERSION_BUMP = "1"

device_driver(
    name = _DRIVER_NAME,
    srcs = [
        "nvme_pcie.c",
        "nvme_pcie_adapter.c",
        "nvme_pcie_debug.c",
        "nvme_pcie_driver.c",
        "nvme_pcie_mgmt.c",
        "nvme_pcie_module.c",
        "nvme_pcie_os.c",
    ],
    binary_compat = _BINARY_COMPAT,
    copts = [
        "-Werror=unused-variable",
    ],
    defines = [
        'NVME_PCIE_DRIVER_VERSION=\\"%s\\"' % _DRIVER_VER,
        'NVME_PCIE_DRIVER_RELEASE=\\"%s\\"' % _VERSION_BUMP,
    ],
    license = "BSD",
    vendor = _VENDOR,
    version = _DRIVER_VER,
    version_bump = _VERSION_BUMP,
)

binary_payload_metadata = add_binary_payload(
    name = "{}-binary".format(_DRIVER_NAME),
    payload_srcs = [":stripped-{}".format(_DRIVER_NAME)],
)

device_spec_metadata = define_device_spec(
    name = "{}-device-def".format(_DRIVER_NAME),
    device_spec_list = [
        NVME_PCIE_DEV,
    ],
)

driver_package(
    name = "{}-vib".format(_DRIVER_NAME),
    acceptance_level = "certified",
    binary_compat = _BINARY_COMPAT,
    binary_payload_metadata = binary_payload_metadata,
    component_name_spec = {
        "name": "VMware-NVMe-PCIe",
        "uistring": "VMware NVMe PCI Express Storage Driver",
    },
    description = "Non-Volatile memory controller driver",
    device_spec_metadata = device_spec_metadata,
    esxio_vibs = True,
    live_install_allowed = False,
    live_remove_allowed = False,
    maintenance_mode = True,
    overlay = False,
    payload = [
        ":{}-binary".format(_DRIVER_NAME),
        ":{}-device-def".format(_DRIVER_NAME),
    ],
    platforms = [{"productLineID": "ESXi"}],
    stateless_ready = True,
    summary = "Non-Volatile memory controller driver",
    vendor = _VENDOR,
    vendor_code = "VMW",
    vendor_email = "support@vmware.com",
    version = _DRIVER_VER,
    version_bump = _VERSION_BUMP,
)
